# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b21aca46e8800e385c37a2669b5a03e97b44a2dbdc2b31192bb2cb5ad342e8e9f6652e17bcf6ea7b3ead9345f971ec9dada63dfdb2b3879e0b8304e4de21f739

test:
  secret_key_base: e82acb53a225d810b4ffa3277c821cdd7997e6be0d93614979be21ef0ad9388ed14cdf8f648921e92179e50759b06ec56c6e81c3057baed6272b63783b261ce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
